import assert from "node:assert/strict";
import { test } from "node:test";

import { loadConfig } from "../src/config.ts";
import { buildFfmpegArguments } from "../src/runtime.ts";

test("publishes one raw X11 and Pulse capture directly as RTMP", async () => {
  const config = await loadConfig({
    SOURCE_URL: "https://example.com/player",
    RTMP_URL: "rtmp://ingest.example.com/live/stream-key",
  });

  assert.deepEqual(buildFfmpegArguments(config), [
    "-hide_banner",
    "-nostdin",
    "-loglevel",
    "warning",
    "-thread_queue_size",
    "512",
    "-use_wallclock_as_timestamps",
    "1",
    "-f",
    "x11grab",
    "-draw_mouse",
    "0",
    "-framerate",
    "30",
    "-video_size",
    "1280x720",
    "-i",
    ":99.0+0,0",
    "-thread_queue_size",
    "512",
    "-use_wallclock_as_timestamps",
    "1",
    "-f",
    "pulse",
    "-i",
    "browser.monitor",
    "-map",
    "0:v:0",
    "-map",
    "1:a:0",
    "-c:v",
    "libx264",
    "-preset",
    "veryfast",
    "-tune",
    "zerolatency",
    "-profile:v",
    "main",
    "-level:v",
    "3.1",
    "-pix_fmt",
    "yuv420p",
    "-r",
    "30",
    "-fps_mode",
    "cfr",
    "-g",
    "60",
    "-keyint_min",
    "60",
    "-sc_threshold",
    "0",
    "-b:v",
    "3000k",
    "-maxrate",
    "3000k",
    "-bufsize",
    "6000k",
    "-c:a",
    "aac",
    "-profile:a",
    "aac_low",
    "-b:a",
    "128k",
    "-ar",
    "48000",
    "-ac",
    "2",
    "-af",
    "aresample=async=1:first_pts=0",
    "-flvflags",
    "no_duration_filesize",
    "-flush_packets",
    "1",
    "-progress",
    "pipe:3",
    "-f",
    "flv",
    "rtmp://ingest.example.com/live/stream-key",
  ]);
});
