name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Linting
      run: pnpm lint:ci

    - name: Build
      run: pnpm build

    - name: Install examples dependencies
      run: >
        cd examples/http-server && pnpm install &&
        cd ../record-to-file && pnpm install

    - name: Type checking examples
      run: pnpm tsc:examples
